vital_site/authoring/urls.py
from django.conf.urls import url

from . import views

app_name = 'authoring'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^courses/home/$', views.course_home, name='course_home'),
    url(r'^courses/create/$', views.course_create, name='course_create'),
    url(r'^courses/addvms', views.course_add_vms, name='course_add_vms'),
    url(r'^courses/networking', views.course_networking, name='course_networking'),
    url(r'^courses/summary', views.course_summary, name='course_summary'),
    url(r'^courses/vms/$', views.course_vm_setup, name='course_vms'),
    url(r'^courses/destroy/$', views.course_destroy, name='course_destroy'),
#    url(r'^courses/(?P<course_id>[0-9]+)/destroy/$', views.course_destroy, name='course_destroy'),
    url(r'^courses/upload/$', views.upload_iso, name='upload_iso'),
]

vital_site/authoring/forms/create_form.py
from django.forms import ModelForm
from django import forms
#from datetime import datetime
import datetime
from vital.models import Virtual_Machine_Type, Course, Virtual_Machine


class CreateCourseForm(forms.Form):
    course_name = forms.CharField(widget=forms.widgets.TextInput)
    course_number = forms.CharField(widget=forms.widgets.TextInput)
    #start_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'datepicker'}), initial=date.today)
    #start_date = forms.DateTimeField()


class CreateVmsForm(forms.Form):
    vm_name = forms.CharField(widget=forms.widgets.TextInput)
    vm_type = forms.ModelChoiceField(queryset=Virtual_Machine_Type.objects.all())


class CreateNetworksForm(forms.Form):
    hub_name = forms.CharField(widget=forms.widgets.TextInput)
    hub_vms = forms.ModelChoiceField(queryset=Virtual_Machine.objects.all())
    vm_iface = forms.CharField(widget=forms.widgets.TextInput)

    def __init__(self, course_id, *args, **kwargs):
        super(CreateNetworksForm, self).__init__(*args, **kwargs)
        self.fields['hub_vms'].queryset = Virtual_Machine.objects.filter(course=course_id)

vital_site/authoring/views/create_view.py
from django.shortcuts import render, redirect
import logging
from django import forms
import ConfigParser
from vital.utils import get_notification_message
from vital.models import Registered_Course, Course, Virtual_Machine, Virtual_Machine_Type, Network_Configuration, \
    Registered_Course
from ..forms import CreateCourseForm, CreateVmsForm, CreateNetworksForm
from django.utils.crypto import get_random_string
from django.http import HttpResponseRedirect, HttpResponse
from subprocess import Popen, PIPE
#from datetime import datetime, date
import datetime

logger = logging.getLogger(__name__)
config_ini = ConfigParser.ConfigParser()
config_ini.optionxform = str

# TODO change to common config file in shared location
config_ini.read("/home/vital/config.ini")


def index(request):
    return redirect('/authoring/courses/home/')


def course_home(request):
    """
    lists all active courses for faculty
    :param request: http request
    :return: active courses page
    """
    logger.debug("In course home")
    created_courses = Course.objects.filter(course_owner=request.user.id)
    reg_courses = Registered_Course.objects.filter(user_id=request.user.id)
    request.session['notification'] = get_notification_message()
    message = ''
    if len(created_courses) == 0:
        message = 'You have no active courses'
    if len(reg_courses) == 0:
        message = 'You have no registered courses'
    return render(request, 'authoring/course_home.html', {'created_courses': created_courses,
                                                          'reg_courses': reg_courses, 'message': message})


def course_create(request):
    logger.debug("in course create - " + request.method)
    error_message = ''
    if request.method == 'POST':
        form = CreateCourseForm(request.POST)
        if form.is_valid():
            course = Course()
            course.name = form.cleaned_data['course_name']
            course.course_number = form.cleaned_data['course_number']
            #course.start_date = form.cleaned_data['start_date']
            #course.created_date = datetime.date.today
            user_id = request.user.id
            course.course_owner = user_id
            reg_code = get_random_string(length=8)
            course.registration_code = reg_code
            course.save()
            request.session['course_id'] = course.id
            return redirect('/authoring/courses/addvms')
    else:
        form = CreateCourseForm()
    return render(request, 'authoring/course_create.html', {'form': form, 'error_message': error_message})


def course_add_vms(request):
    logger.debug("in course add vms")
    error_message = ''
    course_id = request.session.get('course_id', None)
    created_vms = Virtual_Machine.objects.filter(course=course_id)
    if request.method == 'POST':
        form = CreateVmsForm(request.POST)
        if form.is_valid():
            vm = Virtual_Machine()
            vm.course = Course.objects.get(id=course_id)
            vm.name = form.cleaned_data['vm_name']
            vm.type = form.cleaned_data['vm_type']
            vm.save()
            if request.POST.get("next"):
                return redirect('/authoring/courses/networking')
            elif request.POST.get("cancel"):
                return redirect('/authoring/courses/home')
            else:
                form = CreateVmsForm()
    else:
        form = CreateVmsForm()
    return render(request, 'authoring/course_add_vms.html', {'created_vms': created_vms, 'form': form,
                                                             'error_message': error_message})


def course_networking(request):
    logger.debug("in course networking")
    error_message = ''
    course_id = request.session.get('course_id', None)
    created_nets = Network_Configuration.objects.filter(course=course_id)
    if request.method == 'POST':
        form = CreateNetworksForm(course_id, request.POST)
        if form.is_valid():
            net = Network_Configuration()
            net.name = form.cleaned_data['hub_name']
            net.course = Course.objects.get(id=course_id)
            net.virtual_machine = form.cleaned_data['hub_vms']
            net.interface = form.cleaned_data['vm_iface']
            net.save()
            if request.POST.get("next"):
                return redirect('/authoring/courses/summary')
            elif request.POST.get("cancel"):
                return redirect('/authoring/courses/home')
            else:
                form = CreateNetworksForm(course_id)
    else:
        form = CreateNetworksForm(course_id)
    return render(request, 'authoring/course_networking.html', {'created_nets': created_nets,
                                                                'form': form, 'error_message': error_message})


def course_summary(request):
    logger.debug("in course summary")
    message = ''
    course_id = request.session.get('course_id', None)
    course_name = Course.objects.get(id=course_id)
    vms = Virtual_Machine.objects.filter(course=course_id)
    hubs = Network_Configuration.objects.filter(course=course_id)
    if request.method == 'POST':
        logger.debug("activating course" + course_id)
        cmd = 'sudo /home/vital/vital2.0/source/virtual_lab/vital_site/scripts/sftp_account.sh '+course_id
        p = Popen(cmd.split(), stdout=PIPE, stderr=PIPE)
        out, err = p.communicate()
        if p.returncode == 0:
            course_name.status = 'ACTIVE'
            message = 'Course have been successfully activated'
            return redirect('/authoring/courses/home')
        else:
            logger.debug("Course not activated")
            raise Exception('ERROR : cannot activate course. \n Reason : %s' % err.rstrip())

    return render(request, 'authoring/course_summary.html', {'course_name': course_name, 'vms': vms, 'hubs': hubs,
                                                             'message': message})


def course_vm_setup(request):
    return HttpResponse('you are on the course vm setup page')


def course_destroy(request):
    message = ''
    return HttpResponse('you are on the course destroy page')


def upload_iso(request):
    return HttpResponse('you are on the iso upload page')

vital_site/authoring/templates/authoring/course_add_vms.html
{% extends 'vital/base.html' %}

{% block content %}
<form action="{% url 'authoring:course_add_vms' %}" method='POST' id="form">
    {% csrf_token %}
    {% if error_message %}
    <p class="error">
            {{ error_message }}
    </p>
    {% endif %}

    {% if created_vms %}
        {%  for created_vm in created_vms %}
            <div style="width: 100%" align="left">
                <table width="75%" style="font-size: small">
                    <tr>
                        <td> {{ created_vm.name }}</td>
                        <td> {{ created_vm.type }} </td>
                    </tr>
                </table>
            {% endfor %}
    {% endif %}

    <table style="width: auto">
    {% for field in form %}
        <tr>
            <td><label for="{{ field.auto_id }}">{{ field.label_tag }}
            <td>{{ field }}</td>

            {% if field.name == 'vm_type' %}
                <td><a href="{% url 'authoring:upload_iso' %}">Upload iso</a></td>
            {% endif %}
            {% if field.errors %}
                <td colspan="2" align="right">
		          {% for error in field.errors %}
		            <div style="font-size: 10px; color: red" align="right">{{ error }}</div>
		          {% endfor %}
                  </td>
            {% endif %}
        </tr>
    {% endfor %}
    <tr>
        <td colspan="3" align="right"><input type='submit' value='Add more' name="addmore"/>
    </tr>
    <tr>
        <td colspan="3" align="right"><input type='submit' value='Next' name="next"/></td>
        <td colspan="3" align="right"><input type='submit' value='Cancel' name="cancel"/></td>
    </tr>
    </table>

</form>

<!--<script>
function addmore(){
    var contents = document.getElementById("form");
    var cln = contents.cloneNode(true);
    document.getElementById("form").appendChild(cln);
}
</script>-->


{% endblock content %}

vital_site/authoring/templates/authoring/course_create.html
{% extends 'vital/base.html' %}

{% block content %}

<form action="{% url 'authoring:course_create' %}" method='POST'>
    {% csrf_token %}
    {% if error_message %}
    <p class="error">
            {{ error_message }}
    </p>
    {% endif %}
    <table style="width: auto">
    {% for field in form %}
        <tr>
            <td><label for="{{ field.auto_id }}">{{ field.label_tag }}
            <td>{{ field }}</td>
            {% if field.start_date %}
                <td class="datepicker"></td>
            {% endif %}
            {% if field.errors %}
                <td colspan="2" align="right">
		          {% for error in field.errors %}
		            <div style="font-size: 10px; color: red" align="right">{{ error }}</div>
		          {% endfor %}
                  </td>
            {% endif %}
        </tr>
    {% endfor %}
    <tr>
        <td colspan="3" align="right"><input type='submit' value='Next'/></td>
    </tr>
    </table>
</form>

 <!--   {% load static %}
    <script type="text/javascript" src="{% static 'authoring/js/jquery-ui.min.js' %}"></script>
    <link rel="Stylesheet" type="text/css" href={% static "authoring/js/jquery-ui.min.css"%}/>
    <link rel="Stylesheet" type="text/css" href={% static "authoring/js/jquery-ui.structure.min.css"%}/>
    <link rel="Stylesheet" type="text/css" href={% static "authoring/js/jquery-ui.theme.min.css"%}/>

    <script>
      $(function() {
        $( '.datepicker' ).datepicker({dateFormat : 'yy-mm-dd'});

      });
    </script>-->


{% endblock content %}

vital_site/authoring/templates/authoring/course_home.html
{% extends 'vital/base.html' %}

{% block content_without_center %}
    <div id="center" align="center" style="width: 800px">
{% if message %} <p style="color: green">{{ message }}&nbsp;&nbsp;&nbsp;<a href="/authoring/courses/create">Create a new course</a></p> {% endif %}
      {% if created_courses %}
      <div style="width: 100%" align="left">
          <div style="width: 50%;float: left"><h5 style="padding-left: 10px"> Active Courses </h5></div>
          <div style="width: 50%;float: left;" align="right"><a href="/authoring/courses/create">Create course</a></div></div>
            <table width="75%" style="font-size: small">
            <tr style="background-color: #d2bfde; color: white">
                <th width="30%">Course</th>
                <th width="20%">Course Number</th>
                <th width="30%">Start Date</th>
                <th width="20%">&nbsp;</th>
            </tr>
            {% for created_course in created_courses %}
                <tr>{% if created_course.status == "ACTIVE" %}
                        <td><a href="{% url 'authoring:course_vms' %}">{{ created_course.name }}</a></td>
                    {% else %}
                        <td title="Course is inactive.">{{ created_course.name }}</td>
                    {% endif %}
                    <td>{{ created_course.course_number }}</td>
                    <td>{{ created_course.start_date }}</td>
                    <td><a href="{% url 'authoring:course_destroy' %}">Destroy</a></td>
                </tr>
            {% endfor %}
            </table>
      {% endif %}
    </div>
    {% if message %} <p style="color: green">{{ message }}&nbsp;&nbsp;&nbsp;<a href="/vital/courses/register">Register for a new course</a></p> {% endif %}
    <div style="width: 100%" align="left">
    {% if reg_courses %}
        <div style="width: 50%;float: left"><h5 style="padding-left: 10px"> Registered Courses </h5></div>
        <div style="width: 50%;float: left;" align="right"><a href="/vital/courses/register">Register</a></div></div>
        <table width="75%" style="font-size: small">
            <tr style="background-color: #d2bfde; color: white">
                <th width="30%">Course</th>
                <th width="20%">Course Number</th>
                <th width="30%">Start Date</th>
                <th width="20%">&nbsp;</th>
            </tr>
            {% for reg_course in reg_courses %}
                <tr>{% if reg_course.course.status == "ACTIVE" %}
                        <td><a href="{% url 'authoring:course_vms' %}">{{ reg_course.course.name }}</a></td>
                    {% else %}
                        <td title="Course is inactive.">{{ reg_course.course.name }}</td>
                    {% endif %}
                    <td>{{ reg_course.course.course_number }}</td>
                    <td>{{ reg_course.course.start_date }}</td>
                    <td><a href="{% url 'authoring:course_destroy' %}">Remove</a></td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}
    </div>
{% endblock content_without_center %}

vital_site/authoring/templates/authoring/course_networking.html
{% extends 'vital/base.html' %}

{% block content %}
    <form action="{% url 'authoring:course_networking' %}" method='POST'>
        {% csrf_token %}

        {% if error_message %}
            <p class="error">
                {{ error_message }}
            </p>
        {% endif %}

        {% if created_nets %}
            {% for created_net in created_nets %}
                <div style="width: 100%" align="left">
                    <table width="75%" style="font-size: small">
                        <tr>
                            <td>{{ created_net.name }}</td>
                            <td>{{ created_net.virtual_machine }}</td>
                            <td>{{ created_net.interface }}</td>
                        </tr>
                    </table>
                </div>
            {% endfor %}
        {% endif %}

        <table style="width: auto">
            <tr>
                <td><label for="{{ form.hub_name.id_for_label }}">Hub name</label>
                <td>{{ form.hub_name }}</td>
            </tr>
            <tr>
                <td><label for="{{ form.hub_vms.id_for_label }}">VM name</label>
                <td>{{ form.hub_vms }}</td>
                <td><label for="{{ form.vm_iface.id_for_label }}">Iface</label>
                <td>{{ form.vm_iface }}</td>
            </tr>

        {% if field.errors %}
            <td colspan="2" align="right">
              {% for error in field.errors %}
                <div style="font-size: 10px; color: red" align="right">{{ error }}</div>
              {% endfor %}
              </td>
        {% endif %}

            <tr>
                <td colspan="4" align="right"><input type='submit' value='Add more VMs' name="addmore"/></td>
                <td colspan="3" align="right"><input type='submit' value='Add more Hubs' name="addmore"/>
            </tr>
            <tr>
                <td colspan="4" align="right"><input type='submit' value='Next' name="next"/></td>
                <td colspan="4" align="right"><input type='submit' value='Cancel' name="cancel"/></td>
            </tr>
        </table>
    </form>
{% endblock content %}

vital_site/authoring/templates/authoring/course_summary.html
{% extends 'vital/base.html' %}

{% block content %}
    <form>
    <table>
        <tr>
            <td colspan="3" align="right"><input type='submit' value='Activate' name="activate"/>
        </tr>
    </table>
    </form>

{% endblock content %}

vital_site/authoring/templates/vital/index.html
<html>
<body>
hello world!
</body>
</html>