vital_site/vital_site/vital_site/vital/urls.py
from django.conf.urls import url

from . import views

app_name = 'vital'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^courses/register/$', views.register_for_course, name='course_register'),
    url(r'^courses/(?P<course_id>[0-9]+)/deregister/$', views.unregister_from_course, name='course_deregister'),
    url(r'^courses/(?P<course_id>[0-9]+)/vms/$', views.course_vms, name='course_vms'),
    url(r'^courses/(?P<course_id>[0-9]+)/virtual_machines/$', views.virtual_machines, name='virtual_machines'),
    url(r'^courses/(?P<course_id>[0-9]+)/detail/$', views.course_detail, name='course_detail'),
    url(r'^console/(?P<vm_id>[0-9]+)/$', views.console, name='console'),
    url(r'^courses/registered/$', views.registered_courses, name='registered_courses'),
    url(r'^courses/advising/$', views.advising_courses, name='advising_courses'),
    url(r'^users/register/$', views.register, name='user_register'),
    url(r'^users/activate/$', views.activate, name='user_activate'),
    url(r'^users/(?P<user_id>[0-9]+)/vms/(?P<vm_id>[0-9]+)/release-vm/$', views.release_vm, name='user_releaseVM'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^users/reset-password', views.reset_password, name='user_reset_password'),
    url(r'^users/forgot-password', views.forgot_password, name='user_forgot_password'),
    url(r'^courses/(?P<course_id>[0-9]+)/vms/(?P<vm_id>[0-9]+)/start', views.start_vm, name='start_vm'),
    url(r'^courses/(?P<course_id>[0-9]+)/vms/(?P<vm_id>[0-9]+)/stop', views.stop_vm, name='stop_vm'),
    url(r'^courses/(?P<course_id>[0-9]+)/vms/(?P<vm_id>[0-9]+)/rebase', views.rebase_vm, name='rebase_vm'),
]

vital_site/vital_site/vital_site/vital_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^vital/', include('vital.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^captcha/', include('captcha.urls')),
    url(r'session_security/', include('session_security.urls')),
]

vital_site/vital_site/vital_site/vital/models.py
from __future__ import unicode_literals

from django.db import models
from datetime import datetime
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin


class CustomUserManager(BaseUserManager):
    def create_user(self, email,
                    password=None):
        user = self.model(email=email, password=password)
        user.set_password(user.password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email,
                         password):
        user = self.create_user(email,
                                password=password)
        user.set_password(user.password)
        user.is_staff = True
        user.is_admin = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class Department(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Intake_Period(models.Model):
    period_name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.period_name


class VLAB_User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField('email address', unique=True, db_index=True)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    admitted_on = models.ForeignKey(Intake_Period, null=True, blank=True)
    department = models.ForeignKey(Department, null=True)
    phone = models.CharField(max_length=200, null=True)
    is_active = models.BooleanField(default=False)
    activation_code = models.CharField(max_length=50, null=True)
    is_staff = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_faculty = models.BooleanField(default=False)
    created_date = models.DateTimeField(default=datetime.now, blank=True)
    sftp_account = models.CharField(max_length=200, unique=True)
    sftp_pass = models.CharField(max_length=200)
    USERNAME_FIELD = 'email'

    objects = CustomUserManager()

    def get_full_name(self):
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        return self.first_name

    def __unicode__(self):
        return self.email

# class Blocked_User(models.Model):
#    user_id = models.IntegerField(default=0)
#    blocked_at = models.DateTimeField(default=datetime.now)


class User_Session(models.Model):
    user_id = models.IntegerField(default=0, unique=True)
    session_key = models.CharField(max_length=40)


class Allowed_Organization(models.Model):
    name = models.CharField(max_length=200, unique=True)
    email_suffix = models.CharField(max_length=200)


class Course(models.Model):
    name = models.CharField(max_length=200)
    course_number = models.CharField(max_length=200, unique=True)
    registration_code = models.CharField(max_length=10, unique=True)
    capacity = models.IntegerField(default=0)
    start_date = models.DateTimeField(default=datetime.now, blank=True)
    created_date = models.DateTimeField(default=datetime.now, blank=True)
    status = models.CharField(max_length=10)
    auto_shutdown_after = models.IntegerField(default=3)
    allow_long_running_vms = models.BooleanField(default=False)
    no_of_students = models.IntegerField(default=0)

    def __str__(self):
        return self.course_number + ":" + self.name


class Virtual_Machine_Type(models.Model):
    name = models.CharField(max_length=200)
    icon_location = models.CharField(max_length=500)


class Virtual_Machine(models.Model):
    course = models.ForeignKey(Course)
    name = models.CharField(max_length=200)
    type = models.ForeignKey(Virtual_Machine_Type, null=True)


class User_VM_Config(models.Model):
    xen_server = models.CharField(max_length=50)
    vm = models.ForeignKey(Virtual_Machine)
    user_id = models.IntegerField(default=0)
    vnc_port = models.CharField(max_length=10)
    terminal_port = models.CharField(max_length=10)
    no_vnc_pid = models.CharField(max_length=10)
    token = models.CharField(max_length=50, null=True)


class Available_Config(models.Model):
    category = models.CharField(max_length=20)
    value = models.CharField(max_length=200)


class Network_Configuration(models.Model):
    name = models.CharField(max_length=10)
    course = models.ForeignKey(Course)
    virtual_machine = models.ForeignKey(Virtual_Machine)
    is_course_net = models.BooleanField(default=False)
    has_internet_access = models.BooleanField(default=False)


class User_Bridge(models.Model):
    name = models.CharField(max_length=50, primary_key=True)
    created = models.BooleanField(default=False)


class User_Network_Configuration(models.Model):
    vm = models.ForeignKey(Virtual_Machine)
    course = models.ForeignKey(Course)
    user_id = models.IntegerField(default=0)
    bridge = models.ForeignKey(User_Bridge)
    mac_id = models.CharField(max_length=50)
    is_course_net = models.BooleanField(default=False)


class Faculty(models.Model):
    PROFESSOR = 'PR'
    TEACHING_ASSISTANT = 'TA'
    OWNER = 'OW'
    TYPE_CHOICES = (
        (PROFESSOR, 'Professor'),
        (TEACHING_ASSISTANT, 'TeachingAssistant'),
        (OWNER, 'Owner')
    )
    course = models.ForeignKey(Course)
    user = models.ForeignKey(VLAB_User, null=True)
    type = models.CharField(max_length=2, choices=TYPE_CHOICES, default=PROFESSOR)


class Registered_Course(models.Model):
    user_id = models.IntegerField(default=0)
    course = models.ForeignKey(Course)
    registered_date = models.DateTimeField(default=datetime.now)


class Audit(models.Model):
    done_by = models.IntegerField()
    done_at = models.DateTimeField(default=datetime.now)
    action = models.CharField(max_length=500)


class Xen_Server(models.Model):
    name = models.CharField(max_length=50, unique=True)
    total_memory = models.IntegerField(default=0)
    used_memory = models.IntegerField(default=0)
    utilization = models.DecimalField(max_digits=5, decimal_places=4)
    no_of_vms = models.IntegerField(default=0)
    no_of_students = models.IntegerField(default=0)
    no_of_courses = models.IntegerField(default=0)
    status = models.CharField(max_length=10)


class Auto_Start_Resources(models.Model):
    name = models.CharField(max_length=15, unique=True)
    type = models.CharField(max_length=10)
    course = models.ForeignKey(Course)


#adding new tables for maintaing student local network MAC id's
class Local_Network_MAC_Address(models.Model):
    course = models.ForeignKey(Course)
    network_configuration = models.ForeignKey(Network_Configuration)
    mac_id = models.CharField(max_length=200)

vital_site/vital_site/vital_site/vital/forms/security_form.py
from django.forms import ModelForm, TextInput
from django import forms
from ..models import VLAB_User
from captcha.fields import CaptchaField
from passwords.fields import PasswordField


class Registration_Form(ModelForm):

    cleaned_data = {}
    # password = forms.CharField(widget=forms.PasswordInput)
    password = PasswordField(label="Password")
    confirm_password = forms.CharField(widget=forms.PasswordInput)
    captcha = CaptchaField()
    phone = forms.CharField(required=False)

    class Meta:
        model = VLAB_User
        fields = ['email', 'first_name', 'last_name', 'password', 'confirm_password', 'admitted_on', 'department',
                  'phone', 'captcha']

    def clean(self):
        cleaned_data = super(Registration_Form, self).clean()
        if 'password' in self.cleaned_data and 'confirm_password' in self.cleaned_data:
            if self.cleaned_data['password'] != self.cleaned_data['confirm_password']:
                raise forms.ValidationError("Passwords don't match. Please enter both fields again.")
        return self.cleaned_data


class Forgot_Password_Form(forms.Form):
    email = forms.EmailField(widget=forms.widgets.TextInput)
    captcha = CaptchaField()


class User_Activation_Form(forms.Form):
    code = forms.CharField(widget=TextInput())
    user_email = forms.CharField(widget=forms.HiddenInput())


class Authentication_Form(forms.Form):
    email = forms.EmailField(widget=forms.widgets.TextInput)
    password = forms.CharField(widget=forms.widgets.PasswordInput)

    class Meta:
        fields = ['email', 'password']


class Reset_Password_Form(forms.Form):
    password = PasswordField(label="Password")
    confirm_password = forms.CharField(widget=forms.PasswordInput)
    user_email = forms.CharField(widget=forms.HiddenInput())
    activation_code = forms.CharField(widget=forms.HiddenInput())

    def clean(self):
        cleaned_data = super(Reset_Password_Form, self).clean()
        if 'password' in self.cleaned_data and 'confirm_password' in self.cleaned_data:
            if self.cleaned_data['password'] != self.cleaned_data['confirm_password']:
                raise forms.ValidationError("Passwords don't match. Please enter both fields again.")
        return self.cleaned_data

vital_site/vital_site/vital_site/vital/forms/student_form.py
from django import forms


class Course_Registration_Form(forms.Form):
    course_registration_code = forms.CharField(widget=forms.TextInput())

vital_site/vital_site/vital_site/vital/views/faculty_view.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from ..models import Faculty, Course, Virtual_Machine, Registered_Course
import logging

logger = logging.getLogger(__name__)


@login_required(login_url='/vital/login/')
def advising_courses(request):
    logger.debug("In registered courses")
    faculty_records = Faculty.objects.filter(user_id=request.user.id)
    adv_courses = []
    for faculty in faculty_records:
        logger.debug(faculty)
        adv_courses.append(faculty.course)
    return render(request, 'vital/advising_courses.html', {'advising_courses': adv_courses})


@login_required(login_url='/vital/login/')
def course_detail(request, course_id):
    logger.debug("in course detail")
    professors = ''
    teaching_assistants = ''
    is_prof = False
    faculty_self = Faculty.objects.filter(course_id=course_id, user_id=request.user.id)
    if len(faculty_self) == 1 and faculty_self[0].type == 'PR':
        is_prof = True

    try:
        course = Course.objects.get(pk=course_id)
        faculties = course.faculty_set.all()
        for faculty in faculties:
            if faculty.type == 'OW' or faculty.type == 'PR':
                professors = professors + ',' + ("%s %s" % (faculty.user.first_name, faculty.user.last_name))
            else:
                teaching_assistants = teaching_assistants + ', ' + ("%s %s" % (faculty.user.first_name, faculty.user.last_name))
        virtual_machines = Virtual_Machine.objects.filter(course_id=course_id)
        students_registered = len(Registered_Course.objects.filter(course_id=course_id))
    except Course.DoesNotExist:
        logger.error("Course being searched for cannot be found - course id:%d, user id:%d" % (course_id,
                                                                                               request.user.id))
    return render(request, 'vital/course_detail.html', {'virtual_machines': virtual_machines, 'course': course,
                                                        'professors': professors[1:],
                                                        'students_registered': students_registered,
                                                        'teaching_assistants': teaching_assistants[1:],
                                                        'is_prof':is_prof})

vital_site/vital_site/vital_site/vital/templates/vital/advising_courses.html
{% extends 'vital/base.html' %}

{% block content_without_center %}
    <div id="center" align="center" style="width: 800px">
      {% if advising_courses %}
      <div style="width: 100%" align="left">
          <div style="width: 50%;float: left"><h5 style="padding-left: 10px"> Advising Courses </h5></div></div>
            <table width="75%" style="font-size: small">
            <tr style="background-color: #d2bfde; color: white">
                <th width="30%">Course</th>
                <th width="20%">Course Number</th>
                <th width="30%">Start Date</th>
                <th width="20%">Registration Code</th>
            </tr>
            {% for course in advising_courses %}
                <tr><td><a href="{% url 'vital:course_detail' course.id %}">{{ course.name }}</a></td>
                    <td>{{ course.course_number }}</td>
                    <td>{{ course.start_date }}</td>
                    <td>{{ course.registration_code }}</td>
                </tr>
            {% endfor %}
            </table>
      {% else %}
          <p style="color: green">You have no courses to advise.&nbsp;&nbsp;&nbsp;<a href="#">Request for new course</a></p>
      {% endif %}
    </div>
{% endblock content_without_center %}

vital_site/vital_site/vital_site/vital/templates/vital/course_detail.html
{% extends 'vital/base.html' %}
{% load staticfiles %}
{% block content_without_center %}
    <script type="application/javascript">
    function windowpop(url, name, width, height) {
    var leftPosition, topPosition;
    //Allow for borders.
    leftPosition = (window.screen.width / 2) - ((width / 2) + 10);
    //Allow for title and status bars.
    topPosition = (window.screen.height / 2) - ((height / 2) + 50);
    //Open the window.
    window.open(url, name,
            "status=no,height=" + height + ",width=" + width + ",resizable=yes,left=" + leftPosition
            + ",top=" + topPosition + ",screenX=" + leftPosition + ",screenY=" + topPosition
            + ",toolbar=no,menubar=no,scrollbars=no,location=no,directories=no");return false;
}
    </script>
<style type="text/css">

    .button {
    background-color: white;
    color: black;
    border: 2px solid #d2bfde;
    padding: 5px 10px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 12px;
    }
    .button:hover {
    background-color: #d2bfde;
    color: white;
    text-decoration: none;
    }

    .button:active {
       text-decoration: none;
    }

    #center{
        width : 800px
    }
	.box {
	    border:1px solid #ccc;
	    margin:20px;
	    height:120px;
	    width:140px;
		float:left;
	}
	.overlay {
	    background:rgba(0, 0, 0, .5);
	    text-align:center;
	    opacity:0;
	    width:100%;height:100%;
	    -webkit-transition: all 0.3s ease-in-out;
	    -moz-transition: all 0.3s ease-in-out;
	    -o-transition: all 0.3s ease-in-out;
	    -ms-transition: all 0.3s ease-in-out;
	    transition: all 0.3s ease-in-out;
	}
	.box:hover {
	    border:1px solid #555;
	    border-radius:5px;
	}
	.box:hover .overlay {
	    opacity:1;
	}
    </style>
    <style>
        table, th, td {
            border: 1px solid #d2bffe;
            font-size: 12px;
        }
    </style>

    <div id="center" align="center" style="width: 800px">
        {% if course %}
            <table>
            <tr><td style="background-color: #d2bfde;">Course Name</td><td>{{ course.name }}</td>
                <td style="background-color: #d2bfde;">Course Number</td><td>{{ course.course_number }}</td></tr>
            <tr><td style="background-color: #d2bfde;">Status</td><td>{{ course.status }}</td>
                <td style="background-color: #d2bfde;">Registration Code</td><td>{{ course.registration_code }}</td></tr>
            <tr><td style="background-color: #d2bfde;">Created On</td><td>{{ course.created_date }}</td>
                <td style="background-color: #d2bfde;">Start On</td><td>{{ course.start_date }}</td></tr>
            <tr><td style="background-color: #d2bfde;">Capacity</td><td>{{ course.capacity }}</td>
                <td style="background-color: #d2bfde;">Currently Registered</td><td>{{ students_registered }}</td></tr>
            <tr><td style="background-color: #d2bfde;">Professors</td><td>{% if professors %}{{ professors }}{% else %} None Assigned {% endif %}</td>
                <td style="background-color: #d2bfde;">Teaching Assistants</td><td>{% if teaching_assistants %}{{ teaching_assistants }}{% else %} None Assigned {% endif %}</td></tr>
            {% if is_prof %}
                <tr><td colspan="4" align="right">
                    {% if course.status == 'ACTIVE' %}
                        <a href="#" class="button">End Course</a>
                    {% else %}
                        <a href="#" class="button">Start Course</a>
                    {% endif %}
                </td></tr>
            {% endif %}
            </table>
            <br />
            {% if virtual_machines %}
                <div style="width: 75%">
                <table>
                {% for vm in virtual_machines %}<tr><td width="100px">
                <div class="box" style='background:url({% static  vm.type.icon_location %}) no-repeat 50% 50%;background-size: contain;'
                     title={{ vm.name }}>
		            <div class="overlay" style="width:100%;height:100%">
	                    <div style="height:33%;padding-top:7px">
                            <a href='/vital/console/dummy' onclick="return windowpop(this.href,'Terminal1', 545, 320)">
                                <img src="{% static  'vital/power-red.png' %}" width="30px" height="30px" title="Start VM"/>
                            </a>
                        </div>
                        <div style="float:left;width:33%;height:33%;" align="left">
                            <a href=#2>
                                <img src="{% static  'vital/save-state.png' %}" width="30px" height="30px" title="Save state"/>
                            </a></div>
                        <div style="float:left;width:33%;height:33%;" align="center">
                            <a href="/vital/console/dummy" onclick="return windowpop(this.href, 'Terminal2', 545, 320)">
                                <img src="{% static  'vital/console.ico' %}" width="30px" height="30px" title="View console"/>
                            </a>
                        </div>
                        <div style="float:left;width:33%;height:33%;" align="right">
                            <a href=#3>
                                <img src="{% static  'vital/backup-restore.png' %}" width="30px" height="30px" title="Restore state"/>
                            </a>
                        </div>
                        <div style="height:33%;vertical-align:center">
                            <a href=#4>
                                <img src="{% static  'vital/reimage.png' %}" width="30px" height="30px" title="Reimage VM"/>
                            </a>
                        </div>
		            </div>
		            <div style="width:100%; margin-top:-5px; font-weight:bold" align="center">{{ vm.name }}</div>
		        </div>
                    </td>
                <td>
                <table>
                    <tr><td>Base Image : {{ vm.base_image.name }}</td><td>Memory : {{ vm.base_image.memory }}MB</td></tr>
                    <tr><td>Backing File : {{ vm.base_image.backing_file }}</td><td>Reimage File : {{ vm.base_image.reimage_file }}</td></tr>
                    <tr><td>Network Config</td>
                        <td>{% if vm.network_configuration_set.all %}
                    {% for conf in vm.network_configuration_set.all%}
                        {{ conf.name }}<br/>
                    {% endfor %}
                {% endif %}</td></tr>
                </table>
                </td>
                </tr>
                {% endfor %}
                </table>
                </div>
            {% endif %}
        {% else %}
            <div style="color: red"> Cannot find the course you are looking for!</div>
        {% endif %}
     </div>

{% endblock content_without_center %}

vital_site/vital_site/vital_site/vital/templates/vital/course_register.html
{% extends 'vital/base.html' %}
{% block content %}

<script>
$(document).ready(setup);

function setup () {
    $('form').submit(function() {
        $(this).find('input[type="submit"]').prop('disabled', true);
    });
}
</script>

<div style="width: 100%" align="left">
    <h5 style="padding-left: 20px"> Register for course </h5>
</div>

{% if message %}
<p style="color: green">{{ message }}</p> {% endif %}
<form action="{% url 'vital:course_register' %}" method='POST'>
    {% csrf_token %} 
    {% if error_message %}
    <p class="error">
        {{ error_message }}
    </p>
    {% endif %}
    <table style="width: auto">
        {% for field in form.visible_fields %}
        <tr>
            <td>{{ field.label_tag }}</td>
            <td>{{ field }}</td>
            {% if field.errors %}
            <td colspan="2" align="right">
                {% for error in field.errors %}
                <div style="font-size: 10px; color: red" align="right">{{ error }}</div>
                {% endfor %}
            </td>
            {% endif %}
        </tr>
        {% endfor %}
        <tr>
            <td colspan="2" align="right">
                <input type='submit' value='Register' onclick="openNav()"/>
            </td>
        </tr>
    </table>
</form>
{% endblock content %}

vital_site/vital_site/vital_site/vital/templates/vital/course_vms.html
{% extends 'vital/base.html' %}
{% load staticfiles %}
{% block content_without_center %}
    <script type="application/javascript">
    function refresh() {
        $.ajax({
            url: "{% url 'vital:virtual_machines' course_id %}",
            success: function(data) {
                $('#vms').html(data);
            }
        });
        setTimeout(refresh, 5000);
    }

    $(function(){
        refresh();
    });

    function windowpop(url, name, width, height, vm_id) {
    var leftPosition, topPosition;
    //Allow for borders.
    leftPosition = (window.screen.width / 2) - ((width / 2) + 10);
    //Allow for title and status bars.
    topPosition = (window.screen.height / 2) - ((height / 2) + 50);
    //Open the window.
    window_child = window.open(url, name,
            "status=no,height=" + height + ",width=" + width + ",resizable=yes,left=" + leftPosition
            + ",top=" + topPosition + ",screenX=" + leftPosition + ",screenY=" + topPosition
            + ",toolbar=no,menubar=no,scrollbars=no,location=no,directories=no");
        console.log('save vm'+vm_id);
    sessionStorage.setItem('window_'+vm_id, window_child);
        return false;
    };


$(window).load(function(){
    $("#message").delay(4000).fadeOut();
});
    </script>
<style type="text/css">
    #center{
        width : 800px
    }
	.box {
	    border:1px solid #ccc;
	    margin:20px;
	    height:120px;
	    width:140px;
		float:left;
	}
	.overlay {
	    background:rgba(0, 0, 0, .5);
	    text-align:center;
	    opacity:0;
	    width:100%;height:100%;
	    -webkit-transition: all 0.3s ease-in-out;
	    -moz-transition: all 0.3s ease-in-out;
	    -o-transition: all 0.3s ease-in-out;
	    -ms-transition: all 0.3s ease-in-out;
	    transition: all 0.3s ease-in-out;
	}
	.box:hover {
	    border:1px solid #555;
	    border-radius:5px;
	}
	.box:hover .overlay {
	    opacity:1;
	}
    </style>

    {% if message %}
           <div id="message" style="position: absolute; width:65%; height:25px; background-color: #ddea91;
           z-index: 1100; top:160px; font-size: small; color: darkred">{{ message }}</div>
       {% endif %}
<div id = "vms">
    {% include "virtual_machines.html" %}
</div>

{% endblock content_without_center %}

vital_site/vital_site/vital_site/vital/templates/vital/dummy.html
<html>
<body bgcolor="black">
{% include 'session_security/all.html' %}
<div style="color: #00aa00; font-size: small">
THIS IS A DUMMY HTML PAGE TO MIMIC CONSOLE LOOK AND FEEL.<br/><br/>
Last login: Tue Jan 19 10:53:18 on ttys003<br/>
You have new mail.<br/>
server@vital.poly.edu:~ admin$
</div>
</body>
</html>

vital_site/vital_site/vital_site/vital/templates/vital/forgot_password.html
{% extends 'vital/base.html' %}

{% block content %}
<div style="width: 100%" align="left"><h5 style="padding-left: 20px"> Forgot your password? </h5></div>

{% if message %} <p style="color: green">{{ message }}</p> {% endif %}
<form action="{% url 'vital:user_forgot_password' %}" method='POST'>
    {% csrf_token %}
{% if error_message %}
<p class="error">
        {{ error_message }}
</p>
{% endif %}
    <table style="width: auto">
        {% for field in form.visible_fields %}
            <tr>
            <td>{{ field.label_tag }}</td>
            <td>{{ field }}</td>
            {% if field.errors %}
		          <td colspan="2" align="right">
		          {% for error in field.errors %}
		            <div style="font-size: 10px; color: red" align="right">{{ error }}</div>
		          {% endfor %}
                  </td>
		        {% endif %}
            </tr>
        {% endfor %}
    <tr><td colspan="2" align="right"><input type='submit' value='Reset Password'/></td></tr>
    </table>
</form>
{% endblock content %}

vital_site/vital_site/vital_site/vital/templates/vital/login.html
{% extends 'vital/base.html' %}

{% block content %}
    {% if message %} <p style="color: green">{{ message }}</p> {% endif %}
<form action="{% url 'vital:login' %}" method='POST' style="width: 300px">
    {% csrf_token %}
    {% if error_message %}
    <p class="error">
            {{ error_message }}
    </p>
    {% endif %}
    <table style="width: auto">
        {% for field in form %}
            <tr>
            <td>{{ field.label_tag }}</td>
            <td>{{ field }}</td>
            </tr>
        {% endfor %}
    <tr><td colspan="3" align="right"><input type='submit' value='Login'/></td></tr>
    </table>
    <hr style="width: 80%"/>
    <div style="width: 100%;font-size:small" align="center">
        <a href="{% url 'vital:user_forgot_password' %}">Can't access your account?</a>
    </div>
    <br />
    <div style="width: 100%;font-size:small" align="center">
        New to Vital? <br/><a href="{% url 'vital:user_register' %}">Signup for a new account</a>
    </div>
</form>
{% endblock content %}

vital_site/vital_site/vital_site/vital/templates/vital/registered_courses.html
{% extends 'vital/base.html' %}

{% block content_without_center %}
    <div id="center" align="center" style="width: 800px">
{% if message %} <p style="color: green">{{ message }}&nbsp;&nbsp;&nbsp;<a href="/vital/courses/register">Register for new course</a></p> {% endif %}
      {% if reg_courses %}
      <div style="width: 100%" align="left">
          <div style="width: 50%;float: left"><h5 style="padding-left: 10px"> Registered Courses </h5></div>
          <div style="width: 50%;float: left;" align="right"><a href="/vital/courses/register">Add course</a></div></div>

            <table width="75%" style="font-size: small">
            <tr style="background-color: #d2bfde; color: white">
                <th width="30%">Course</th>
                <th width="20%">Course Number</th>
                <th width="30%">Start Date</th>
                <th width="20%">&nbsp;</th>
            </tr>
            {% for reg_course in reg_courses %}
                <tr>{% if reg_course.course.status == "ACTIVE" %}
                        <td><a href="{% url 'vital:course_vms' reg_course.course.id %}">{{ reg_course.course.name }}</a></td>
                        {% else %}
                        <td title="Course is inactive. Contact Faculty.">{{ reg_course.course.name }}</td>
                        {% endif %}
                    <td>{{ reg_course.course.course_number }}</td>
                    <td>{{ reg_course.course.start_date }}</td>
                    <td><a href="{% url 'vital:course_deregister' reg_course.course.id %}">Remove</a></td>
                </tr>
            {% endfor %}
            </table>
      {% endif %}
    </div>
{% endblock content_without_center %}